export const ROUTES = {
  home: '/',
  about: '/about',
  contact: '/contact',
  reviews: '/reviews',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  login: '/login',
  register: '/register',
  packages: {
    hajj: '/packages/hajj',
    umrah: '/packages/umrah',
    detail: (type: string, slug: string) => `/packages/${type}/${slug}`,
  },
  transportation: {
    root: '/transportation',
    detail: (slug: string) => `/transportation/${slug}`,
  },
  booking: {
    root: '/booking',
    confirmation: (code: string) => `/booking/${code}`,
    success: (code: string) => `/booking/success/${code}`,
  },
  admin: {
    root: '/admin',
    packages: '/admin/packages',
    transports: '/admin/transports',
    pilgrims: '/admin/pilgrims',
    bookings: '/admin/bookings',
    bookingDetail: (id: string) => `/admin/bookings/${id}`,
    payments: '/admin/payments',
    invoices: '/admin/invoices',
    invoiceNew: '/admin/invoices/new',
    invoiceDetail: (id: string) => `/admin/invoices/${id}`,
    reviews: '/admin/reviews',
    inquiries: '/admin/inquiries',
    users: '/admin/users',
    reports: '/admin/reports',
    media: '/admin/media',
    settings: '/admin/settings',
    content: {
      root: '/admin/content',
      hero: '/admin/content/hero',
      faqs: '/admin/content/faqs',
    },
  },
  pilgrim: {
    root: '/pilgrim',
    bookings: '/pilgrim/bookings',
    bookingDetail: (code: string) => `/pilgrim/bookings/${code}`,
    payments: '/pilgrim/payments',
    installments: '/pilgrim/installments',
    documents: '/pilgrim/documents',
    invoices: '/pilgrim/invoices',
    profile: '/pilgrim/profile',
    notifications: '/pilgrim/notifications',
    visa: '/pilgrim/visa',
  },
} as const
