export const ROUTES = {
  home: '/',
  about: '/about',
  contact: '/contact',
  blog: '/blog',
  reviews: '/reviews',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  refund: '/refund',
  login: '/login',
  register: '/register',
  packages: {
    hajj: '/packages/hajj',
    umrah: '/packages/umrah',
    detail: (type: string, slug: string) => `/packages/${type}/${slug}`,
  },
  admin: {
    root: '/admin',
    packages: '/admin/packages',
    pilgrims: '/admin/pilgrims',
    bookings: '/admin/bookings',
    payments: '/admin/payments',
    reviews: '/admin/reviews',
    inquiries: '/admin/inquiries',
    users: '/admin/users',
    reports: '/admin/reports',
    media: '/admin/media',
    settings: '/admin/settings',
    content: {
      root: '/admin/content',
      hero: '/admin/content/hero',
      faqs: '/admin/content/faqs',
      blogs: '/admin/content/blogs',
    },
  },
  pilgrim: {
    root: '/pilgrim',
    bookings: '/pilgrim/bookings',
    flight: '/pilgrim/flight',
    hotel: '/pilgrim/hotel',
    payments: '/pilgrim/payments',
    installments: '/pilgrim/installments',
    documents: '/pilgrim/documents',
    invoices: '/pilgrim/invoices',
    profile: '/pilgrim/profile',
    notifications: '/pilgrim/notifications',
    visa: '/pilgrim/visa',
  },
} as const
